stockpilot:
  outputs:
    dev:
      dataset: stock_analytics_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /app/keys/gcp_key.json
      # keyfile: /home/wohnungpb6/code/stockpilot-investment-analysis-app/keys/gcp_key.json
      location: EU
      method: service-account
      priority: interactive
      project: stockpilot-app-478511
      threads: 2
      type: bigquery
  target: dev
