FROM python:3.12.8-slim

WORKDIR /app
RUN apt-get update && apt-get install -y \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV GOOGLE_APPLICATION_CREDENTIALS="stockpilot/gcp-key.json"

ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ENABLECORS=false
ENV STREAMLIT_SERVER_ENABLEXSRF_PROTECTION=false

EXPOSE 8501

CMD ["streamlit","run","app.py","--server.address=0.0.0.0"]
